---
- name: "Patching MediaServer"
  ansible.buildin.import_tasks: mediaserver.yml
  when: ip_address == "{{ mediaserver }}"

- name: "Patching Linux Ubuntu node {{ hostname }}"
  ansible.buildin.import_tasks: ubuntu.yml
  when: os_name == "Ubuntu" and os_family == "Debian" and ip_address in ubuntu_linux_nodes

