---
- name: "Patching MediaServer"
  ansible.builtin.import_tasks: mediaserver.yml
  when: ip_address == mediaserver
  become: yes

- name: "Patching Linux Ubuntu/Debian node {{ hostname }}"
  ansible.builtin.import_tasks: ubuntu.yml
  when: os_family == "Debian" and ip_address in ubuntu_linux_nodes
  become: yes

