---
ip_address: "{{ ansible_default_ipv4.address }}"
os_family: "{{ ansible_os_family }}"
os_version: "{{ ansible_distribution_version }}"
os_name: "{{ ansible_distribution }}"
hostname: "{{ ansible_hostname }}"
confirm_update: true